- 08/16 2021     1. Add v4l-ctl checks before executing in scripts/yolov4-realtime.

diff --git a/scripts/yolov4-realtime b/scripts/yolov4-realtime
--- a/scripts/yolov4-realtime
+++ b/scripts/yolov4-realtime
@@ -1,6 +1,18 @@
 #!/bin/bash
 
-devices=$(v4l2-ctl --list-devices 2>&1 | grep 'Intel(R) RealSense(TM) Depth Ca')
+export v4l2_status=$(which v4l2-ctl)
+
+if [[ "$v4l2_status" == '' ]]
+then
+	echo 'Command v4l2-ctl NOT found.'
+	echo ''
+	echo 'You can install it with'
+	echo '$ sudo apt install v4l-utils'
+	echo ''
+	exit 1
+fi
+
+export devices=$(v4l2-ctl --list-devices 2>&1 | grep 'Intel(R) RealSense(TM) Depth Ca')
 
 if [[ "$devices" == '' ]]
 then
